version: "3.3"

# make sure that docker machine has enough memory to run the cluster.
# setting it up to 4GB seems to work.

services:

  cassandra-seed:
    image: cassandra:latest
#    ports:
#      - "9042:9042"
    volumes:
      - "cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
#    restart: always


  cassandra1:
    image: cassandra:latest
    volumes:
      - "cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra-seed
#    restart: always

  cassandra2:
    image: cassandra:latest
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
#      needed for setting up custom cluster name
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - cassandra-seed
#    restart: always

volumes:
  cassandra_data_seed:
  cassandra_data_1:
  cassandra_data_2:



# version: '2'

# services: 
#  cas1: 
#     container_name: casssandra1
#     image: cassandra:latest
#     volumes:
#       - $(pwd)/data:/var/lib/cassandra:/var/lib/cassandra
#     ports:
#       - 9042:9042
#     environment:
#       - CASSANDRA_START_RPC=true
#       - CASSANDRA_CLUSTER_NAME=MyCluster
#       - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#       - CASSANDRA_DC=datacenter1
#  cassandra2:
#   container_name: cassandra2
#   image: cassandra:latest
#   volumes:
#       - $(pwd)/data2:/var/lib/cassandra:/var/lib/cassandra
#   ports:
#       - 9043:9042
#   command: bash -c 'sleep 60;  /docker-entrypoint.sh cassandra -f'
#   depends_on:
#     - cassandra1
#   environment:
#       - CASSANDRA_START_RPC=true
#       - CASSANDRA_CLUSTER_NAME=MyCluster
#       - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
#       - CASSANDRA_DC=datacenter1
#       - CASSANDRA_SEEDS=cas1